---
title: "Example"
output: html_document
---

```{r, include=FALSE}
library(ggplot2)
library(gridExtra)
library(cowplot)
```

```{r Dose 26ALL, include=FALSE}
Data=read.csv("Dose26.csv")
str(Data)
head(Data)
```

```{r}
Data$Pedigree <-factor(Data$Pedigree, levels=c("R", "S", "F1", "F2", "BC"), labels=c("R", "S", "SR/F1", "F2", "BC/S"))


Data$Survival<-factor(Data$Survival, levels=c("Died", "High", "Medium", "Low"), labels=c("Dead (>99%)", "High (80 to 98%)", "Medium (40 to 79%)", "Low (<40%)"))
```





```{r Violin Pl, echo=FALSE}
p1<-ggplot(Data, aes(y=Biomass, x=Pedigree)) + 
geom_violin(fill="grey95") +
  scale_color_manual(values=c("black", "red", "blue", "darkgreen"), name="Plant injury level") +
geom_jitter(aes(color=Survival), shape=1, width = .02) + 
  labs(fill="", y="Biomass (g)", x="") +
  coord_cartesian(ylim = c(0, 0.85)) +
  theme(axis.text=element_text(size=12, color="black"),
        axis.title=element_text(size=18, face="bold"), 
        panel.background = element_rect(fill="white", color = "black"), 
        panel.grid.major = element_line(color = "white"), axis.text.x=element_text(angle=20,hjust=1),
  panel.grid.minor = element_blank(), panel.border=element_rect(fill=NA, color="black", size=0.7, linetype = "solid"), plot.margin = unit(c(0, 0.1, -0.2, 0), "cm"),
  legend.position=c(0.86,0.79))  +
  annotate("text", x = 1.7, y = 0.82, alpha=1, label =as.character(expression(italic(paste("Below-label mesotrione dose (26 g ai ha "^"-1",")")))), parse=T, size=5) + ggsave("Figure1.tiff", device = NULL, path = NULL,
  scale = 1, units="in", width=10, height=5, dpi=300)
```


```{r Dose 26, include=FALSE}
Data=read.csv("Dose26.csv")
str(Data)
head(Data)
```

```{r}
Data$Population <-factor(Data$Population, levels=c("R", "S", "F1-8", "F1-9", "F1-13", "F2-9", "F2-13", "BC-8", "BC-9", "BC-13"), labels=c("R", "S", "SR/F1-8", "SR/F1-9", "SR/F1-13", "F2-9", "F2-13", "BC-8/S", "BC-9/S", "BC-13/S"))


Data$Survival<-factor(Data$Survival, levels=c("Died", "High", "Medium", "Low"), labels=c("Dead (>99%)", "High (80 to 98%)", "Medium (40 to 79%)", "Low (<40%)"))
```

```{r Violin Plot, echo=FALSE}
ggplot(Data, aes(y=Biomass, x=Population)) + 
geom_violin(fill="grey95") +
  scale_color_manual(values=c("black", "red", "blue", "darkgreen"), name="Plant injury level") +
geom_jitter(aes(color=Survival), shape=1, width = .02) + 
  labs(fill="", y="Biomass (g)", x="") +
  coord_cartesian(ylim = c(0, 0.85)) +
  theme(axis.text=element_text(size=12, color="black"), 
        axis.title=element_text(size=18, face="bold"), 
        panel.background = element_rect(fill="white", color =NA), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(), panel.border=element_rect(fill=NA, color="black", size=0.7, linetype = "solid"), plot.margin = unit(c(0, 0.1, -0.4, 0), "cm"), axis.text.x=element_text(angle=20,hjust=1),
  legend.position=c(0.86,0.79), legend.text = element_text(size = 12, colour = "black"), legend.title = element_text(size = 12, face="bold", colour = "black"), legend.key = element_rect(size=3, fill=NA),
legend.background = element_rect(fill =NA)) +
  annotate("text", x = 1.3, y = 0.82, alpha=1, label =as.character(expression(italic(paste("26 g ai ha "^"-1","")))), parse=T, size=5) + ggsave("Figure2.tiff", device = NULL, path = NULL,
  scale = 1, units="in", width=8, height=5, dpi=300)
```
