---
title: "Violin in one Figure"
author: "Maxwel C. Oliveira"
date: "May 1, 2017"
output: html_document
---

```{r, include=FALSE}
library(ggplot2)
library(gridExtra)
library(cowplot)
```

```{r Dose 26ALL, include=FALSE}
Data=read.csv("Dose26.csv")
str(Data)
head(Data)
```

```{r}
Data$Pedigree <-factor(Data$Pedigree, levels=c("R", "S", "F1", "F2", "BC"), labels=c("R", "S", "SR/F1", "F2", "BC/S"))


Data$Survival<-factor(Data$Survival, levels=c("Died", "High", "Medium", "Low"), labels=c("Dead (>98%)", "High (80 to 98%)", "Medium (40 to 79%)", "Low (<40%)"))
```



c(top, right, bottom, left)

```{r Violin Pl, echo=FALSE}
p1<-ggplot(Data, aes(y=Biomass, x=Pedigree)) + 
geom_violin(fill="grey95") +
  scale_color_manual(values=c("black", "red", "blue", "darkgreen"), name="Plant injury level") +
geom_jitter(aes(color=Survival), shape=1, width = .02) + 
  labs(fill="", y="Biomass (g)", x="") +
  coord_cartesian(ylim = c(0, 0.85)) +
  theme(axis.text=element_text(size=12, color="black"),
        axis.title=element_text(size=18, face="bold"), 
        panel.background = element_rect(fill="white", color = "black"), 
        panel.grid.major = element_line(color = "white"), axis.text.x=element_text(angle=20,hjust=1),
  panel.grid.minor = element_blank(), panel.border=element_rect(fill=NA, color="black", size=0.7, linetype = "solid"), plot.margin = unit(c(0, 0.1, -0.2, 0), "cm"),
  legend.position=c(1.90,6.5))  +
  annotate("text", x = 2.1, y = 0.82, alpha=1, label =as.character(expression(italic(paste("Below-label mesotrione dose (26 g ai ha "^"-1",")")))), parse=T, size=5) 
```


```{r Dose 26, include=FALSE}
Data=read.csv("Dose26.csv")
str(Data)
head(Data)
```

```{r}
Data$Population <-factor(Data$Population, levels=c("R", "S", "F1-8", "F1-9", "F1-13", "F2-9", "F2-13", "BC-8", "BC-9", "BC-13"), labels=c("R", "S", "SR/F1-8", "SR/F1-9", "SR/F1-13", "F2-9", "F2-13", "BC-8/S", "BC-9/S", "BC-13/S"))


Data$Survival<-factor(Data$Survival, levels=c("Died", "High", "Medium", "Low"), labels=c("Dead (>98%)", "High (80 to 98%)", "Medium (40 to 79%)", "Low (<40%)"))
```

```{r Violin Plot, echo=FALSE}
p2<-ggplot(Data, aes(y=Biomass, x=Population)) + 
geom_violin(fill="grey95") +
  scale_color_manual(values=c("black", "red", "blue", "darkgreen"), name="Plant injury level") +
geom_jitter(aes(color=Survival), shape=1, width = .02) + 
  labs(fill="", y="", x="") +
  coord_cartesian(ylim = c(0, 0.85)) +
  theme(axis.text=element_text(size=12, color="black"), 
        axis.text.y=element_blank(),
        axis.title=element_text(size=18, face="bold"), 
        panel.background = element_rect(fill="white", color =NA), 
        panel.grid.major = element_line(color = "white"), 
  panel.grid.minor = element_blank(), panel.border=element_rect(fill=NA, color="black", size=0.7, linetype = "solid"), plot.margin = unit(c(0, 0.1, -0.4, 0), "cm"), axis.text.x=element_text(angle=20,hjust=1),
  legend.position=c(0.86,0.79), legend.text = element_text(size = 12, colour = "black"), legend.title = element_text(size = 12, face="bold", colour = "black"), legend.key = element_rect(size=3, fill=NA),
legend.background = element_rect(fill =NA)) +
  annotate("text", x = 1.3, y = 0.82, alpha=1, label =as.character(expression(italic(paste("26 g ai ha "^"-1","")))), parse=T, size=5) 
```

```{r Dose 105, include=FALSE}
Data1=read.csv("Dose105.csv") 
str(Data1)
```

```{r}
Data1$Pedigree <-factor(Data1$Pedigree, levels=c("R", "S", "F1", "F2", "BC"), labels=c("R", "S", "SR/F1", "F2", "BC/S"))


Data1$Survival<-factor(Data1$Survival, levels=c("Died", "High", "Medium", "Low"), labels=c("Dead (100%)", "High (80 to 99%)", "Medium (40 to 79%)", "Low (<40%)"))
```


```{r Violin Plot, echo=FALSE}
p3<-ggplot(Data1, aes(y=Biomass, x=Pedigree)) + 
geom_violin(fill="grey95") +
  scale_color_manual(values=c("black", "red", "blue", "darkgreen"), name="Plant injury level") +
geom_jitter(aes(color=Survival), shape=1, width = .02) + 
  labs(fill="", y="Biomass (g)", x="") +
   coord_cartesian(ylim = c(0, 0.85)) +
  theme(axis.text=element_text(size=12, color="black"), 
        axis.title=element_text(size=18, face="bold"), 
        panel.background = element_rect(fill="white", color = "black"), 
        panel.grid.major = element_line(color = "white"), axis.text.x=element_text(angle=20,hjust=1),
  panel.grid.minor = element_blank(),  panel.border=element_rect(fill=NA, color="black", size=0.7, linetype = "solid"), plot.margin = unit(c(-0.1, 0.1, -0.2, 0), "cm"),
  legend.position=c(3.0,6.85)) +
  annotate("text", x = 2.5, y = 0.82, alpha=1, label =as.character(expression(italic(paste("Recommended mesotrione label dose  (105 g ai ha "^"-1",")")))), parse=T, size=5) 
```

```{r Dose 105, include=FALSE}
Data1=read.csv("Dose105.csv") 
str(Data1)
```

```{r}
Data1$Population <-factor(Data1$Population, levels=c("R", "S", "F1-8", "F1-9", "F1-13", "F2-9", "F2-13", "BC-8", "BC-9", "BC-13"), labels=c("R", "S", "SR/F1-8", "SR/F1-9", "SR/F1-13", "F2-9", "F2-13", "BC-8/S", "BC-9/S", "BC-13/S"))


Data1$Survival<-factor(Data1$Survival, levels=c("Died", "High", "Medium", "Low"), labels=c("Dead (100%)", "High (>80%)", "Medium (40 to 79%)", "Low (<40%)"))
```

```{r Violin Plot, echo=FALSE}
p4<-ggplot(Data1, aes(y=Biomass, x=Population)) + 
geom_violin(fill="grey95") +
  scale_color_manual(values=c("black", "red", "blue", "darkgreen"), name="Plant injury level") +
geom_jitter(aes(color=Survival), shape=1, width = .02) + 
  labs(fill="", y="", x="") +
   coord_cartesian(ylim = c(0, 0.85)) +
  theme(axis.text=element_text(size=12, color="black"),  panel.border=element_rect(fill=NA, color="black", size=0.7, linetype = "solid"),
        axis.title=element_text(size=18, face="bold"),
        axis.text.y=element_blank(),
        panel.background = element_rect(fill="white", color = "black"), 
        panel.grid.major = element_line(color = "white"), plot.margin = unit(c(-0.1, 0.1, -0.4, 0), "cm"), 
  panel.grid.minor = element_blank(), axis.text.x=element_text(angle=20,hjust=1),
  legend.position=c(8.90,8.85), legend.text = element_text(size = 8, colour = "black"), legend.title = element_text(size = 10, face="bold", colour = "black"), legend.key = element_rect(size=2, fill=NA),
legend.background = element_rect(fill =NA)) +
  annotate("text", x = 1.4, y = 0.82, alpha=1, label =as.character(expression(italic(paste("105 g ai ha "^"-1","")))), parse=T, size=5) 
```


```{r Dose 420, include=FALSE}
Data2=read.csv("Dose420.csv")
str(Data2)
```

```{r}
Data2$Pedigree <-factor(Data2$Pedigree, levels=c("R", "S", "F1", "F2", "BC"), labels=c("R", "S", "SR/F1", "F2", "BC/S"))


Data2$Survival<-factor(Data2$Survival, levels=c("Died", "High", "Medium", "Low"), labels=c("Dead", "High (>80%)", "Medium (40 to 79%)", "Low (<40%)"))
```

c(top, right, bottom, left)

```{r Violin Plot, echo=FALSE}
p5<-ggplot(Data2, aes(y=Biomass, x=Pedigree)) + 
geom_violin(fill="grey95") + 
  scale_color_manual(values=c("black", "red", "blue", "darkgreen"), name="Plant injury level") + 
geom_jitter(aes(color=Survival), shape=1, width = .02) + 
  labs(fill="", y="Biomass (g)", x="Family") + 
   coord_cartesian(ylim = c(0, 0.85)) +
  theme(axis.text=element_text(size=12, color="black"),
        axis.title=element_text(size=18, face="bold"),  
        panel.background = element_rect(fill="white", color = "black"),  
        panel.grid.major = element_line(color = "white"),  
  panel.grid.minor = element_blank(),  panel.border=element_rect(fill=NA, color="black", size=0.7, linetype = "solid"),
  legend.position=c(1.90,4.85), legend.text = element_text(size = 10, colour = "black"), legend.title = element_text(size = 10, face="bold", colour = "black"), legend.key = element_rect(size=2, fill=NA), plot.margin = unit(c(-0.1, 0.1, -0.11, 0), "cm"), axis.text.x=element_text(angle=20,hjust=1),
legend.background = element_rect(fill =NULL)) +
  annotate("text", x = 1.9, y = 0.82, alpha=1, label =as.character(expression(italic(paste("High mesotrione dose (420 g ai ha "^"-1",")")))), parse=T, size=5) 
```

```{r Dose 420, include=FALSE}
Data2=read.csv("Dose420.csv")
str(Data2)
```

```{r}
Data2$Population <-factor(Data2$Population, levels=c("R", "S", "F1-8", "F1-9", "F1-13", "F2-9", "F2-13", "BC-8", "BC-9", "BC-13"), labels=c("R", "S", "SR/F1-8", "SR/F1-9", "SR/F1-13", "F2-9", "F2-13", "BC-8/S", "BC-9/S", "BC-13/S"))

Data2$Survival<-factor(Data2$Survival, levels=c("Died", "High", "Medium", "Low"), labels=c("Dead", "High (>80%)", "Medium (40 to 79%)", "Low (<40%)"))
```

```{r Violin Plot, echo=FALSE}
p6<-ggplot(Data2, aes(y=Biomass, x=Population)) + 
geom_violin(fill="grey95") + 
  scale_color_manual(values=c("black", "red", "blue", "darkgreen"), name="Plant injury level") + 
geom_jitter(aes(color=Survival), shape=1, width = .02) + 
  labs(fill="", y="", x="Family") + 
   coord_cartesian(ylim = c(0, 0.85)) +
  theme(axis.text=element_text(size=12, color="black"),
        axis.title=element_text(size=18, face="bold"), 
        axis.text.y=element_blank(),  panel.border=element_rect(fill=NA, color="black", size=0.7, linetype = "solid"),
        panel.background = element_rect(fill="white", color = "black"),  
        panel.grid.major = element_line(color = "white"),  
  panel.grid.minor = element_blank(), plot.margin = unit(c(-0.1, 0.1, -0.33, 0), "cm"),
  legend.position=c(8.90,8.85), legend.text = element_text(size = 8, colour = "black" ), 
  axis.text.x=element_text(angle=20,hjust=1), legend.title = element_text(size = 10, colour = "black"), legend.key = element_rect(size=2, fill=NA), axis.title.x = element_text(vjust=3),
legend.background = element_rect(fill =NULL)) +
  annotate("text", x = 1.4, y = 0.82, alpha=1, label =as.character(expression(italic(paste("420 g ai ha "^"-1","")))), parse=T, size=5) 
```


```{r}
Y<-plot_grid(p1, p2, p3, p4, p5, p6, nrow=3, ncol=2, vjust=2, labels = c('A', 'B', 'C', 'D', 'E', 'F')) 
```

```{r}
ggsave("sample.tiff", plot = Y, device = NULL, path = NULL,
  scale = 1, units="in", width=14, height=10, dpi=300)
```



